[package]
name = "rwcockpitplugin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
xplm = "0.3"
rwcommon = { version = "0.1", path = "../rwcommon" }